#!/usr/bin/env python3
"""Generate the proposed rename map for journals / essays / case studies
under .agentile/docs/.

Read-only: emits .agentile/INDEX/RENAME_PLAN.md + .agentile/INDEX/RENAME_PLAN.tsv.
Does NOT execute any rename or frontmatter edit. The TSV can be piped to
`apply_rename_plan.py` once the project owner approves.

Convention:
  YYYY-MM-DDTHHMM_<slug>.md   (UTC, no colon, ISO-8601-ish)
"""
from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import find_project_root, parse_frontmatter, to_utc_iso  # noqa: E402

REPO_ROOT = find_project_root()
AGENTILE = REPO_ROOT / ".agentile"
OUT = AGENTILE / "INDEX"
OUT.mkdir(exist_ok=True)

DOCS_DIRS = [
    AGENTILE / "docs" / "journals",
    AGENTILE / "docs" / "essays",
    AGENTILE / "docs" / "case_studies",
]

# Match optional existing date / date+T-prefix at the start of a filename.
# Examples we want to strip:
#   2026-04-29_foo.md
#   2026-04-29-foo.md
#   2026_04_29_foo.md           (legacy underscore-only)
#   2026-03-28T21_foo.md
#   2026-04-07T10_foo.md
#   2026-04-29T1316_foo.md
#   2026-03-20.md               (date-only, no slug — handled separately)
EXISTING_PREFIX_RE = re.compile(
    r"""^
    (?P<date>\d{4}[-_]\d{2}[-_]\d{2})
    (?:T(?P<time>\d{2,4}))?
    [_-]?
    """,
    re.VERBOSE,
)


def git_first_commit_time(rel: str) -> datetime | None:
    cmd = [
        "git",
        "-C",
        str(REPO_ROOT),
        "log",
        "--diff-filter=A",
        "--follow",
        "--format=%aI",
        "--",
        rel,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    lines = [ln for ln in proc.stdout.splitlines() if ln.strip()]
    if not lines:
        return None
    return to_utc_iso(lines[-1])


def slug_from_filename(name: str) -> str:
    """Strip any existing YYYY-MM-DD[Thhmm][_-] prefix and the .md extension.

    For files that are nothing but a date (e.g., `2026-03-20.md` — common in
    early-project journals where the author hadn't yet picked a topic),
    return a sentinel slug `journal_entry` so the rename produces a usable
    filename.
    """
    base = name[:-3] if name.endswith(".md") else name
    m = EXISTING_PREFIX_RE.match(base)
    if m:
        base = base[m.end():]
    base = base.lstrip(" -_.")
    if not base:
        return "journal_entry"
    return base


def proposed_name(dt: datetime, slug: str) -> str:
    return f"{dt.strftime('%Y-%m-%dT%H%M')}_{slug}.md"


def collect() -> list[dict]:
    rows: list[dict] = []
    for d in DOCS_DIRS:
        if not d.exists():
            continue
        for path in sorted(d.glob("*.md")):
            rel = str(path.relative_to(REPO_ROOT))
            text = path.read_text(encoding="utf-8", errors="replace")
            fm = parse_frontmatter(text)
            fm_dt = to_utc_iso(fm.get("created", ""))
            git_dt = git_first_commit_time(rel)
            best = fm_dt or git_dt
            source = "frontmatter" if fm_dt else ("git" if git_dt else "unknown")
            slug = slug_from_filename(path.name)
            new = proposed_name(best, slug) if best else None
            rows.append(
                {
                    "category": d.name,
                    "old_path": rel,
                    "old_name": path.name,
                    "slug": slug,
                    "ts_source": source,
                    "fm_created": fm.get("created", ""),
                    "best_iso": best.strftime("%Y-%m-%dT%H:%M:%SZ") if best else "",
                    "new_name": new or "",
                    "new_path": str(d.relative_to(REPO_ROOT)) + "/" + new if new else "",
                    "rename_needed": "Y" if new and new != path.name else ("N" if new == path.name else "BLOCKED"),
                }
            )
    return rows


def emit(rows: list[dict]) -> None:
    cols = [
        "category",
        "rename_needed",
        "ts_source",
        "best_iso",
        "old_path",
        "new_path",
    ]
    tsv = OUT / "RENAME_PLAN.tsv"
    with tsv.open("w", encoding="utf-8") as f:
        f.write("\t".join(cols) + "\n")
        for r in rows:
            f.write("\t".join(r.get(c, "") for c in cols) + "\n")

    md = OUT / "RENAME_PLAN.md"
    with md.open("w", encoding="utf-8") as f:
        f.write("# Proposed Rename Plan — journals / essays / case studies\n\n")
        f.write(
            "Generated by `scripts/index/build_rename_plan.py`. Read-only — "
            "nothing is renamed until the project owner explicitly runs "
            "`scripts/index/apply_rename_plan.py`.\n\n"
        )
        n_total = len(rows)
        n_rename = sum(1 for r in rows if r["rename_needed"] == "Y")
        n_clean = sum(1 for r in rows if r["rename_needed"] == "N")
        n_blocked = sum(1 for r in rows if r["rename_needed"] == "BLOCKED")
        n_fm = sum(1 for r in rows if r["ts_source"] == "frontmatter")
        f.write(f"Total docs in scope: **{n_total}**  \n")
        f.write(f"Will be renamed: **{n_rename}**  \n")
        f.write(f"Already match the convention: **{n_clean}**  \n")
        f.write(f"Blocked (no usable timestamp): **{n_blocked}**  \n")
        f.write(f"Timestamp source = frontmatter: {n_fm}  \n")
        f.write(f"Timestamp source = git history: {n_total - n_fm - n_blocked}\n\n")

        if not rows:
            f.write("_No docs found under `.agentile/docs/{journals,essays,case_studies}/`._\n")
            return

        for cat in ("journals", "essays", "case_studies"):
            cat_rows = [r for r in rows if r["category"] == cat]
            if not cat_rows:
                continue
            f.write(f"## {cat} ({len(cat_rows)})\n\n")
            f.write("| Action | Source | Best timestamp | Old → New |\n")
            f.write("|---|---|---|---|\n")
            for r in sorted(cat_rows, key=lambda r: r["best_iso"] or "9999"):
                action = {"Y": "RENAME", "N": "keep", "BLOCKED": "BLOCKED"}[r["rename_needed"]]
                f.write(
                    f"| {action} | {r['ts_source']} | {r['best_iso']} | "
                    f"`{r['old_name']}` → `{r['new_name']}` |\n"
                )
            f.write("\n")

    print(f"Wrote {md.relative_to(REPO_ROOT)}")
    print(f"Wrote {tsv.relative_to(REPO_ROOT)}")


def main() -> int:
    rows = collect()
    emit(rows)
    return 0


if __name__ == "__main__":
    sys.exit(main())
